name: 4islam
favicon: null
layout_spectrum: 0.0772948490921408
typography_spectrum: 0.6997079802677035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7390383335296065
  lightness: 0.8841140950098634
  saturation: 0.6975439044181257
  rhythmicContrast: 0.8945411846507341
purpose: []
